name: Build Docker image (Check Only)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:check
